
---
title: "Summary of models"
output: pdf_document
date: '2022-07-08'
---


# Correlation

```{r, echo=FALSE, warning=FALSE,message=FALSE, out.width="80%"}
library(tidyverse)
#install.packages("broom.mixed")
library(broom.mixed)
library(broom)
#install.packages("lmerTest")
library(lmerTest)
library(dplyr)
library(knitr)
library(kableExtra)

Pollinator_Plant<- read.csv("Data/Pollinator_Plant.csv") #402 observaciones
Pollinator_Plant<-Pollinator_Plant[,-1]


#Species out
spp_out <- Pollinator_Plant %>%
  group_by(Plant_gen_sp) %>%
  summarise(Unique_Id = n_distinct(Site_ID)) %>%
  filter(Unique_Id == 1) %>%
  select(Plant_gen_sp) %>% pull(Plant_gen_sp)


#Data with species in more than 1 site
Pollinator_Plant = Pollinator_Plant %>% filter(!Plant_gen_sp %in% spp_out)


# correlation
a<-Pollinator_Plant %>% select(Plant_gen_sp,fruit_proportion, Seeds,Seed_weight,richness,visitatio_rate,Frequency)
a <- mutate_all(a, ~replace(., is.na(.), 0))

a_cor <- a %>%
  group_by(Plant_gen_sp) %>%
  do(cormat = cor(select(., -matches("Plant_gen_sp")))) 

list_1 <- a_cor[[2]]

v <- a_cor[[1]]
names(list_1) <- v

data2 <- do.call(rbind.data.frame, list_1)

corre<-data2 %>%
mutate(newcolum = rownames(data2))%>%
separate(newcolum, into=c('species', 'rows'), extra = "merge", sep = "\\.")%>%
select(species, rows,everything())  %>%
remove_rownames() %>%
  mutate(species = replace(species, duplicated(species), ""))

corre %>% 
   kable(booktabs = TRUE,digits =  4,longtable = T,linesep = c("","","","","","\\addlinespace"),align = "llcccccc") %>%
  kable_styling(font_size = 9,full_width = F)

```

\newpage

# Fruit proportion

Summary of models for fruit proportion per plant species

**Richness**

```{r, echo=FALSE, warning=FALSE,message=FALSE, out.width="100%"}
library(knitr)
library(dplyr)
library(kableExtra)
library(tidyverse)
#install.packages("broom.mixed")
library(broom.mixed)
library(broom)
#install.packages("lmerTest")
library(lmerTest)

Pollinator_Plant<- read.csv("Data/Pollinator_Plant.csv") #402 observaciones
Pollinator_Plant<-Pollinator_Plant[,-1]

#Species out
spp_out <- Pollinator_Plant %>%
  group_by(Plant_gen_sp) %>%
  summarise(Unique_Id = n_distinct(Site_ID)) %>%
  filter(Unique_Id == 1) %>%
  select(Plant_gen_sp) %>% pull(Plant_gen_sp)


#Data with species in more than 1 site
Pollinator_Plant = Pollinator_Plant %>% filter(!Plant_gen_sp %in% spp_out)

#Models _ fruit proportion 
# richnes
ta_f<-Pollinator_Plant %>%
  nest_by(Plant_gen_sp) %>%
  mutate(model = list(glmer(cbind(fruit_formado, Fruit_No)~richness + (1|Site_ID),family=binomial,data)))%>%
  summarise(broom.mixed::tidy(model)) %>%
  ungroup()

opts <- options(knitr.kable.NA = "")

ta_f<-ta_f %>%
  select(-effect, -group)  %>%
  mutate(Plant_gen_sp = replace(Plant_gen_sp, duplicated(Plant_gen_sp), ""))
  
ta_f<-filter(ta_f, !term == "sd__(Intercept)")


ta_f %>% 
    kable(booktabs = TRUE,digits =  4, linesep = c("","\\addlinespace")) %>% 
column_spec(6, bold = ifelse(ta_f$p.value < 0.05, T, F) )

```

\newpage
**Visitation rate**

```{r, echo=FALSE, warning=FALSE,message=FALSE, out.width="100%"}

Pollinator_Plant<- read.csv("Data/Pollinator_Plant.csv") #402 observaciones
Pollinator_Plant<-Pollinator_Plant[,-1]

#Species out
spp_out <- Pollinator_Plant %>%
  group_by(Plant_gen_sp) %>%
  summarise(Unique_Id = n_distinct(Site_ID)) %>%
  filter(Unique_Id == 1) %>%
  select(Plant_gen_sp) %>% pull(Plant_gen_sp)


#Data with species in more than 1 site
Pollinator_Plant = Pollinator_Plant %>% filter(!Plant_gen_sp %in% spp_out)


# visistation rate
ta_f2<-Pollinator_Plant %>%
  nest_by(Plant_gen_sp) %>%
  mutate(model = list(glmer(cbind(fruit_formado, Fruit_No)~visitatio_rate + (1|Site_ID),family=binomial,data)))%>%
  summarise(broom.mixed::tidy(model)) %>%
  ungroup()

opts <- options(knitr.kable.NA = "")

ta_f2<-ta_f2 %>%
  select(-effect, -group)  %>%
  mutate(Plant_gen_sp = replace(Plant_gen_sp, duplicated(Plant_gen_sp), ""))
  
ta_f2<-filter(ta_f2, !term == "sd__(Intercept)")


ta_f2 %>% 
kable(booktabs = TRUE,digits =  4, linesep = c("","\\addlinespace")) %>% 
column_spec(6, bold = ifelse(ta_f2$p.value < 0.05, T, F) )

```

\newpage

# Seed numbers

Summary of models for seed numbers per plant species

**Richness**
```{r, echo=FALSE, warning=FALSE,message=FALSE, out.width="100%"}

Pollinator_Plant<- read.csv("Data/Pollinator_Plant.csv") #402 observaciones
Pollinator_Plant<-Pollinator_Plant[,-1]

#Species out
spp_out <- Pollinator_Plant %>%
  group_by(Plant_gen_sp) %>%
  summarise(Unique_Id = n_distinct(Site_ID)) %>%
  filter(Unique_Id == 1) %>%
  select(Plant_gen_sp) %>% pull(Plant_gen_sp)


#Data with species in more than 1 site
Pollinator_Plant = Pollinator_Plant %>% filter(!Plant_gen_sp %in% spp_out)


#Models _ Seed numbers 
# richness
ta_seed<-Pollinator_Plant %>%
  nest_by(Plant_gen_sp) %>%
  mutate(model = list(lmer(Seeds~richness+(1|Site_ID),data))) %>%
  summarise(broom.mixed::tidy(model)) %>%
  ungroup()

opts <- options(knitr.kable.NA = "")

ta_seed<-ta_seed %>%
  select(-effect, -group)  %>%
  mutate(Plant_gen_sp = replace(Plant_gen_sp, duplicated(Plant_gen_sp), ""))
  
ta_seed<-filter(ta_seed, !term == "sd__(Intercept)" & !term =="sd__Observation")


ta_seed %>% 
kable(booktabs = TRUE,digits =  4, linesep = c("","\\addlinespace")) %>% 
column_spec(7, bold = ifelse(ta_seed$p.value < 0.05, T, F) )

```



\newpage
**Visitation rate**

```{r, echo=FALSE, warning=FALSE,message=FALSE, out.width="100%"}
Pollinator_Plant<- read.csv("Data/Pollinator_Plant.csv") 
Pollinator_Plant<-Pollinator_Plant[,-1]

#Species out
spp_out <- Pollinator_Plant %>%
  group_by(Plant_gen_sp) %>%
  summarise(Unique_Id = n_distinct(Site_ID)) %>%
  filter(Unique_Id == 1) %>%
  select(Plant_gen_sp) %>% pull(Plant_gen_sp)


#Data with species in more than 1 site
Pollinator_Plant = Pollinator_Plant %>% filter(!Plant_gen_sp %in% spp_out)

# visitation rate
ta_seed2<-Pollinator_Plant %>%
  nest_by(Plant_gen_sp) %>%
  mutate(model = list(lmer(Seeds~visitatio_rate+(1|Site_ID),data))) %>%
  summarise(broom.mixed::tidy(model)) %>%
  ungroup()

opts <- options(knitr.kable.NA = "")

ta_seed2<-ta_seed2 %>%
  select(-effect, -group)  %>%
  mutate(Plant_gen_sp = replace(Plant_gen_sp, duplicated(Plant_gen_sp), ""))
  
ta_seed2<-filter(ta_seed2, !term == "sd__(Intercept)" & !term =="sd__Observation")


ta_seed2 %>% 
kable(booktabs = TRUE,digits =  4, linesep = c("","\\addlinespace")) %>% 
column_spec(7, bold = ifelse(ta_seed2$p.value < 0.05, T, F) )
```

\newpage

# Seed weight

Summary of models for seed weight per plant species

**Richness**

```{r, echo=FALSE, warning=FALSE,message=FALSE, out.width="100%"}
Pollinator_Plant<- read.csv("Data/Pollinator_Plant.csv") 
Pollinator_Plant<-Pollinator_Plant[,-1]

#Species out
spp_out <- Pollinator_Plant %>%
  group_by(Plant_gen_sp) %>%
  summarise(Unique_Id = n_distinct(Site_ID)) %>%
  filter(Unique_Id == 1) %>%
  select(Plant_gen_sp) %>% pull(Plant_gen_sp)


#Data with species in more than 1 site
Pollinator_Plant = Pollinator_Plant %>% filter(!Plant_gen_sp %in% spp_out)

#Models _ Seed weight 
# richnes
ta_weight<-Pollinator_Plant %>%
  nest_by(Plant_gen_sp) %>%
  mutate(model = list(lmer(Seed_weight~richness+(1|Site_ID),data))) %>%
  summarise(broom.mixed::tidy(model)) %>%
  ungroup()

opts <- options(knitr.kable.NA = "")

ta_weight<-ta_weight %>%
  select(-effect, -group)  %>%
  mutate(Plant_gen_sp = replace(Plant_gen_sp, duplicated(Plant_gen_sp), ""))
  
ta_weight<-filter(ta_weight, !term == "sd__(Intercept)" & !term =="sd__Observation")

ta_weight %>% 
kable(booktabs = TRUE,digits =  4, linesep = c("","\\addlinespace")) %>% 
column_spec(7, bold = ifelse(ta_weight$p.value < 0.05, T, F) )

```

\newpage

**Visitation rate**

```{r, echo=FALSE, warning=FALSE,message=FALSE, out.width="100%"}
Pollinator_Plant<- read.csv("Data/Pollinator_Plant.csv") 
Pollinator_Plant<-Pollinator_Plant[,-1]

#Species out
spp_out <- Pollinator_Plant %>%
  group_by(Plant_gen_sp) %>%
  summarise(Unique_Id = n_distinct(Site_ID)) %>%
  filter(Unique_Id == 1) %>%
  select(Plant_gen_sp) %>% pull(Plant_gen_sp)


#Data with species in more than 1 site
Pollinator_Plant = Pollinator_Plant %>% filter(!Plant_gen_sp %in% spp_out)

#Models _ Seed weight 
# visistation rate
ta_weight2<-Pollinator_Plant %>%
  nest_by(Plant_gen_sp) %>%
  mutate(model = list(lmer(Seed_weight~visitatio_rate+(1|Site_ID),data))) %>%
  summarise(broom.mixed::tidy(model)) %>%
  ungroup()

opts <- options(knitr.kable.NA = "")

ta_weight2<-ta_weight2 %>%
  select(-effect, -group)  %>%
  mutate(Plant_gen_sp = replace(Plant_gen_sp, duplicated(Plant_gen_sp), ""))
  
ta_weight2<-filter(ta_weight2, !term == "sd__(Intercept)" & !term =="sd__Observation")

ta_weight2 %>% 
kable(booktabs = TRUE,digits =  4, linesep = c("","\\addlinespace")) %>% 
column_spec(7, bold = ifelse(ta_weight2$p.value < 0.05, T, F) )

```

